
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygqqscpsqoyzopwtobyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlncXFzY3BzcW95em9wd3RvYnlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjkyMjMsImV4cCI6MjA2NzkwNTIyM30.PLfnUOPyAyzPecK8OfBgZTlVeLpFbhY4l7LPaPomK7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Configure default email settings
export const EMAIL_CONFIG = {
  FROM_EMAIL: "info@vantive.digital",
  SITE_URL: "https://vantive.digital",
  COMPANY_NAME: "Vantive Digital"
};
